-- STUDENT, ENROL, SUBJECT
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
-- 1. 과목별 평균 점수 출력 (출력 : 과목이름, 평균점수)
SELECT 
    SUB_NAME,AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
GROUP BY SUB_NAME;
-- 2. 학생별 시험 평균 점수 출력. 단 평균 60점 이상만(출력 : 학번, 이름, 평균점수)
SELECT 
    S.STU_NO,STU_NAME,AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO,STU_NAME
HAVING AVG(ENR_GRADE) >= 60;
-- 3. 2개이상의 시험을 본 학생들의 이름, 시험개수 출력
SELECT 
    STU_NAME,COUNT(E.STU_NO)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;
-- 4. '강종영' 교수의 수업을 들은(시험을 본) 학생의 학번, 이름, 학과, 시험점수 출력
SELECT 
    S.STU_NO,STU_NAME,STU_DEPT,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
WHERE SUB_PROF = '강종영';
-- EMP, DEPT, SALGRADE
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;
-- 5. 급여 등급이 3이상인 사람의 사번, 이름, 급여등급 출력
SELECT 
    EMPNO,ENAME,GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
WHERE GRADE >= 3;
-- 6. 직급(JOB) 평균 급여 등급이 3이상인 직급, 급여등급 출력
SELECT 
    JOB,GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
WHERE GRADE >=3
--GROUP BY GRADE;

-- 7. 직급별 평균 급여 등급이 3이상인 사람의 수 출력(직급, 3등급 이상 사람 수)
-- 8. 부서별 평균 급여 출력. 단, 1800 이상인 부서만.(출력 : 부서번호, 부서이름, 평균 급여)