-- 조인
-- STUDENT 테이블의 STU_NO는 PK(유니크 + NOT NULL)
SELECT * FROM STUDENT;
-- ENROL 테이블의 STU_NO는 FK(STUDENT 테이블의 STU_NO를 참조하는 참조 키)
SELECT * FROM ENROL;

-- 조인의 종류눈 여러개(INNER, OUTER-LEET OR RIGHT, CROSS 기타 등등)
--INNER 조인 위주로 시작

-- (학번, 이름, 학과) => STUDENT, (점수) => ENROL
SELECT 
    S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO; -- ON 뒤에 조인 조건

-- 시험 평균점수
SELECT 
    S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT;

-- 각 과목별 점수
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

-- ENROL, SUBJECT 테이블 조인
SELECT *
FROM SUBJECT S
INNER JOIN ENROL E ON S.SUB_NO = E.SUB_NO;

-- (학번, 이름, 학과) => STUDENT, (점수) => ENROL, (과목명) => SUBJECT
SELECT 
    S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
ORDER BY S.STU_NO;

-- 학과별 시험 평균 점수 출력
SELECT 
    STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;

-- 
SELECT * FROM EMP;
SELECT * FROM DEPT;

-- 사번 이름 부서번호 부서이름 출력
-- (사번, 이름) => EMP, (부서이름) => DEPT, (부서번호) => 양쪽
SELECT 
    EMPNO, ENAME, E.DEPTNO, DNAME
FROM EMP E
INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO;

SELECT * FROM EMP;
SELECT * FROM SALGRADE;

-- 조인은 꼭 값이 같은 컬럼끼리 하는건 아니다
-- 사원들의 급여 등급 풀력(사번, 이름, 급여 ,급여등급)
SELECT 
    EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL;

-- 각 부서별 급여 평균 등급 출력
--(부서번호, 부서이름, 급여 등급 출력)
SELECT
    D.DEPTNO, DNAME, AVG(GRADE)
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
GROUP BY D.DEPTNO, DNAME;















