SELECT * FROM STUDENT; 

INSERT INTO STUDENT
VALUES('1234','홍길동',95,85,89);

COMMIT;

SELECT 
    S.*, STU_NAME, 
    (JAVA+ORACLE+HTML) / 3 AS SCORE_AVG,
    ROUND((JAVA+ORACLE+HTML) / 3, 1) AS SCORE_AVG
FROM STUDENT S;

SELECT *
FROM STUDENT;

COMMIT;
