SELECT * FROM STUDENT;
-- 1. STUDENT 테이블에서 키가 큰 상위 5명 출력(중복고려 X, ROWNUM사용)
SELECT *
FROM(
    SELECT T.*, ROWNUM AS NUM
    FROM (
        SELECT S.*
        FROM STUDENT S
        WHERE STU_HEIGHT IS NOT NULL
        ORDER BY STU_HEIGHT DESC
    )T
)T2 WHERE NUM <= 5;
-- 2. STUDENT 테이블에서 키가 큰 상위 5명 출력(RANK사용)
SELECT 
    STU_HEIGHT,
    RANK() OVER(ORDER BY STU_HEIGHT DESC) AS RANK
FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL;

SELECT *
FROM (
    SELECT 
        STU_HEIGHT,
    RANK() OVER(ORDER BY STU_HEIGHT DESC) AS RANK
    FROM STUDENT
    WHERE STU_HEIGHT IS NOT NULL
)WHERE RANK <= 5;