-- PL/SQL(사용자 정의함수, TRIGGER, 프로시저 ..)
-- 선언부(선택), 실행부, 예외처리(선택)
-- 마지막은 '/'로 마무리

-- 숫자 2배로 리턴
DROP Function MULT;
CREATE OR REPLACE FUNCTION MULTI(I_VALUE IN NUMBER)
RETURN NUMBER
IS 
-- 변수 선언(선언부)
BEGIN
-- 실행부
    RETURN I_VALUE * 2;
END;
/

SELECT ENAME, SAL, MULTI(SAL)
FROM EMP;

--
CREATE OR REPLACE FUNCTION DATE_FUNC(I_DATE DATE)
RETURN VARCHAR2
IS
BEGIN
    RETURN TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS');
END;
/

SELECT P.*,DATE_FUNC(CDATETIME) 
FROM TBL_POINT P;

-- DATE_FUNC2
-- DATE_FUNC2(CDATETIME, 'DATE') => 'YYYY-MM-DD'
-- DATE_FUNC2(CDATETIME, 'TIME') => 'HH22:MI:SS'
-- DATE_FUNC2(CDATETIME, 'DATETIME') => 'YYYY-MM-DD HH22:MI:SS'
DROP Function DATE_FUNC2;
CREATE OR REPLACE FUNCTION DATE_FUNC2(I_DATE DATE, I_TYPE VARCHAR2)
RETURN VARCHAR2
IS
    O_DATE VARCHAR2(100);
BEGIN
    IF I_TYPE = 'DATETIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS');
    ELSIF I_TYPE = 'DATE' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD');
    ELSIF I_TYPE = 'TIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'HH24:MI:SS');
    ELSE
        O_DATE := '값오류';
    END IF;
    RETURN O_DATE;
END;
/

SELECT 
    DATE_FUNC2(CDATETIME,'DATETIME'),
    DATE_FUNC2(CDATETIME, 'TIME'),
    DATE_FUNC2(CDATETIME, 'DATE'),
    DATE_FUNC2(CDATETIME, 'ZZZ')
FROM TBL_POINT;

--7번째 자리가 1이거나 3이면 '남자' 리턴 2이거나 4면 '여자' 리턴
-- 글자수가 13글자가 아니거나 1~4 아니면 '알수없음' 리턴
SELECT GENDER_CHECK(JUMIN) 
FROM STU;

CREATE OR REPLACE FUNCTION GENDER_CHECK(I_VALUE VARCHAR2)
RETURN VARCHAR2
IS
    O_VALUE VARCHAR2(100);
BEGIN
    IF LENGTH(I_VALUE) != 13 THEN
        O_VALUE := '알수없음';
    ELSIF SUBSTR(I_VALUE,7 ,1) IN (1, 3) THEN
        O_VALUE := '남자';
    ELSIF SUBSTR(I_VALUE,7 ,1) IN (2, 4) THEN
        O_VALUE := '여자';
    ELSE
        O_VALUE := '알수없음';
    END IF;
    RETURN O_VALUE;
END;
/

--CREATE OR REPLACE FUNCTION GENDER_CHECK(I_VALUE VARCHAR2)
--RETURN VARCHAR2
--IS
--    O_VALUE VARCHAR2(10);
--BEGIN
--    O_VALUE := '알수없음';
--    IF LENGTH(I_VALUE) != 13 AND SUBSTR(I_VALUE,7 ,1) IN (1, 3) THEN
--        O_VALUE := '남자';
--    ELSIF LENGTH(I_VALUE) != 13 AND SUBSTR(I_VALUE,7 ,1) IN (2, 4) THEN
--        O_VALUE := '여자';
--    END IF;
--    RETURN O_VALUE;
--END;
--/

-- 90~100 => A, 80~89 => B, 70~79=> C, 60~69 => D
-- 나머지는 F 음수나 100초과는 없다고 가정
SELECT 
    S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE,
    SCORE_GRADE(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

CREATE OR REPLACE FUNCTION SCORE_GRADE(I_VALUE NUMBER)
RETURN VARCHAR2
IS
    O_VALUE VARCHAR2(100);
BEGIN
    IF I_VALUE BETWEEN 90 AND 100 THEN
        O_VALUE := 'A';
    ELSIF I_VALUE >= 80 THEN
        O_VALUE := 'B';
    ELSIF I_VALUE >= 70 THEN
        O_VALUE := 'C';
    ELSIF I_VALUE >= 60 THEN
        O_VALUE := 'D';
    ELSE
         O_VALUE := 'F';
    END IF;
    RETURN O_VALUE;
END;
/









