-- 트리거
-- 특정(선택) 테이블에 변화가 생겼을 때(DELETE, INSERT, UPDATE)
-- 실행되는 프로시저

-- 샘플 트리거 생성
CREATE OR REPLACE TRIGGER TEMP_TRIGGER
    BEFORE -- 트리거 실행 시점(AFTER OR BEFORE)
    INSERT OR UPDATE ON STUDENT -- STUDENT테이블이 INSERT혹은 UPDATE가 발생했을때 실행된다
    FOR EACH ROW -- 각 행별로 트리거 실행
                --EX) UPDATE로 3명의 정보가 변경되면서 트리거도 실행
BEGIN
    DBMS_OUTPUT.PUT_LINE('변경 전 : ' || :OLD.STU_HEIGHT);
    DBMS_OUTPUT.PUT_LINE('변경 전 : ' || :NEW.STU_HEIGHT);
END;
/
UPDATE STUDENT SET
    STU_HEIGHT = STU_HEIGHT +1
WHERE STU_NAME = '옥한빛';

CREATE TABLE EMP_LOG(
    L_EMONO NUMBER,
    O_SAL NUMBER,
    N_SAL NUMBER,
    O_COMM NUMBER,
    N_COMM NUMBER,
    L_ID VARCHAR2(50),
    EVENT VARCHAR2(50),
    L_TIME DATE
);

CREATE OR REPLACE TRIGGER EMP_TRIGGER
    BEFORE
    INSERT OR UPDATE OR DELETE ON EMP
    FOR EACH ROW
BEGIN
--    IF: NEW.COMM IS NULL OR :NEW.COMM < 0 THEN
--        :NEW.COMM := 0;
--    END IF;
    IF INSERTING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :NEW.SAL, :NEW.SAL, :NEW.COMM, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :OLD.SAL, :NEW.SAL, :OLD.COMM, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U', SYSDATE);        
    ELSIF DELETING THEN
        RAISE_APPLICATION_ERROR(-20002, '사원 데이터 삭제불가');
    END IF;
END;
/

UPDATE EMP SET
    SAL = SAL + 50
WHERE EMPNO = '7499';

COMMIT;

SELECT * FROM EMP_LOG;

INSERT INTO EMP
VALUES(1234,'HONG','SALESMAN','7698',SYSDATE,2000,200,20);

DELETE FROM EMP WHERE EMPNO = 1234;







