-- ROWNUM
SELECT S.*, ROWNUM
FROM STUDENT S
WHERE ROWNUM <= 3;

-- ROWNUM 값이먼저 반영되고 정렬이 되므로 뒤죽박죽 됨
SELECT S.*, ROWNUM
FROM STUDENT S
WHERE STU_HEIGHT IS NOT NULL
ORDER BY STU_HEIGHT DESC;

--
SELECT T.*, ROWNUM
FROM (
    SELECT S.*
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC
)T
WHERE ROWNUM <= 3;

--
SELECT T.*, ROWNUM AS NUM
FROM (
    SELECT S.*
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC
)T;

SELECT *
FROM(
    SELECT T.*, ROWNUM AS NUM
    FROM (
        SELECT S.*
        FROM STUDENT S
        WHERE STU_HEIGHT IS NOT NULL
        ORDER BY STU_HEIGHT DESC
    )T
)T2
WHERE NUM = 3;

-- EMP
SELECT
    JOB,SUM(SAL)AS JOB_SAL
FROM EMP
GROUP BY JOB
ORDER BY JOB_SAL DESC;

SELECT T.*, ROWNUM
FROM(
    SELECT
        JOB,SUM(SAL)AS JOB_SAL
    FROM EMP
    GROUP BY JOB
    ORDER BY JOB_SAL DESC
)T
WHERE ROWNUM = 1;

-- RANK, DENSE_RANK, ROW_NUMBER 함수
SELECT
    ENAME, SAL,
    RANK() OVER(ORDER BY SAL DESC) AS RANK1,
    DENSE_RANK() OVER(ORDER BY SAL DESC) AS RANK2,
    ROW_NUMBER() OVER(ORDER BY SAL DESC, ENAME DESC) AS RANK3
FROM EMP;

--
SELECT
    ENAME, SAL,DEPTNO,
    RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK1
FROM EMP;

SELECT *
FROM(
    SELECT
        ENAME, SAL, DEPTNO,
        RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK1
    FROM EMP
)WHERE RANK1 = 1;



