-- 시퀀스

-- EX) 게시판 => 제목, 내용, 작성자, 작성일, 조회수 등이 필요
-- 게시글번호 : 1
-- 제목 : 오라클 재밌다~~
-- 내용 : 정말 재밌다~~
-- 작성자 : TEST123
-- 작성일 : 2026/09/30
-- 조회수 : 0

CREATE TABLE BOARD(
    BOARDNO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENTS VARCHAR(300),
    USERID VARCHAR2(100),
    CNT NUMBER,
    CDATETIME DATE,
    UDATETIME DATE
);


SELECT * FROM BOARD;

-- 시퀀스 생성
CREATE SEQUENCE TEST_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 99999
    NOCYCLE;
    
SELECT 
    TEST_SEQ.NEXTVAL
FROM DUAL;

CREATE SEQUENCE BOARD_SEQ
    INCREMENT BY 1
    START WITH 1;
    
SELECT * FROM BOARD;

INSERT INTO BOARD
VALUES(BOARD_SEQ.NEXTVAL, '재밌는코딩','ㅋㅋㅋㅋㅋㅋ','TESE123',0,SYSDATE,SYSDATE);

INSERT INTO BOARD
VALUES(BOARD_SEQ.NEXTVAL, '점메추','냉무','QQQ',0,SYSDATE,SYSDATE);
COMMIT;

-- 댓글 테이블
-- 댓글번호(COMMENTNO), 댓글내용(CONTENTS), 작성자(USERID), 작성일(CDATETIME), 수정일(UDATETIME)
DROP TABLE BOARD_COMMENT;
CREATE TABLE BOARD_COMMENT(
    COMMENTNO NUMBER PRIMARY KEY,
    BOARDNO NUMBER,
    CONTENTS VARCHAR2(200),
    USERID VARCHAR2(100),
    CDATETIME DATE,
    UDATETIME DATE
);

CREATE SEQUENCE COMMENT_SEQ
    INCREMENT BY 1
    START WITH 1;

SELECT * FROM BOARD_COMMENT;

INSERT INTO BOARD_COMMENT
VALUES(COMMENT_SEQ.NEXTVAL, 1, 'ㄴㄴㄴ', 'QQQ', SYSDATE, SYSDATE);

-- 각 게시글별 댓글 수 구하기 (없으면 0으로 출력)
SELECT 
    B.BOARDNO, TITLE, B.CONTENTS, COUNT(C.COMMENTNO)
FROM BOARD B
LEFT JOIN BOARD_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE, B.CONTENTS;

SELECT 
    B.*,NVL(C_CNT, 0)AS 댓글개수
FROM BOARD B
LEFT JOIN(
    SELECT BOARDNO, COUNT(*) AS C_CNT
    FROM BOARD_COMMENT
    GROUP BY BOARDNO
)T ON B.BOARDNO = T.BOARDNO;

