--
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.*, ENR_GRADE, SUBJECT_AVG
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN (
    SELECT 
        SUB_NO, AVG(ENR_GRADE) AS SUBJECT_AVG
    FROM ENROL E
    GROUP BY SUB_NO
)T ON E.SUB_NO = T.SUB_NO;

SELECT 
    SUB_NO, AVG(ENR_GRADE) AS SUBJECT_AVG
FROM ENROL E
GROUP BY SUB_NO;
