-- OUTER 조인 (LEFT 위주)
SELECT *
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- 각 학생별 시험 평균 점수 출력, 시험 안본 학생 은 '점수없음' 출력
SELECT 
    S.STU_NO ,STU_NAME,
    NVL(TO_CHAR(AVG(ENR_GRADE)), '점수없음')
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

-- 각 학생들이 본 시험의 수 출력 시험 안본 사람 0으로 출력
SELECT 
    S.STU_NO, STU_NAME,
    COUNT(ENR_GRADE)
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

-- PROFESSOR
SELECT * FROM PROFESSOR;
SELECT * FROM STU;

-- 1. 학생이름 담당교수 이름 출력 담당교수 없으면 '담당없음'으로 출력
SELECT 
    S.NAME,
    NVL(P.NAME, '담당없음')
FROM STU S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO;

-- 2. 각 교수가 담당하고 있는 학생 수 출력 없으면 0으로출력
SELECT 
    P.PROFNO, P.NAME,
    COUNT(STUNO)
FROM PROFESSOR P
LEFT JOIN STU S ON S.PROFNO = P.PROFNO
GROUP BY P.NAME, P.PROFNO;

-- EMP
SELECT * FROM EMP;

-- 부하직원의 수 구하기 없으면 0으로 출력
SELECT 
    E1.ENAME,
    COUNT(E2.EMPNO)
FROM EMP E1
LEFT JOIN EMP E2 ON E1.EMPNO = E2.MGR
GROUP BY E1.EMPNO, E1.ENAME;

--
SELECT 
    NAME, D1.DNAME, NVL(D2.DNAME, '부전공 없음')
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
LEFT JOIN DEPARTMENT D2 ON S.DEPTNO2 = D2.DEPTNO;






















