-- 서브쿼리 : 쿼리안에 또 다른 쿼리
-- =은 무조건 1개
-- IN은 2개이상
SELECT  MAX(STU_HEIGHT)
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE STU_HEIGHT = (
    SELECT  
    MAX(STU_HEIGHT)
    FROM STUDENT
);

-- UNION => 나중에 자세히, 결과 합치는 기능
SELECT  MAX(STU_HEIGHT) AS HEIGHT
FROM STUDENT
UNION
SELECT  MIN(STU_HEIGHT) AS HEIGHT
FROM STUDENT;

--2개이상의 레코드 조건절에서 서브쿼리
SELECT *
FROM STUDENT
WHERE STU_HEIGHT IN (
    SELECT  MAX(STU_HEIGHT) AS HEIGHT
    FROM STUDENT
    UNION
    SELECT  MIN(STU_HEIGHT) AS HEIGHT
    FROM STUDENT
);

--
SELECT
    MAX(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

-- 아래처럼 하면 다른학과에 동일 키를 가진 학생도 조회될 수 있다
SELECT *
FROM STUDENT
WHERE STU_HEIGHT IN(
    SELECT
        MAX(STU_HEIGHT)
    FROM STUDENT
    GROUP BY STU_DEPT
);

--
SELECT *
FROM STUDENT
WHERE (STU_DEPT, STU_HEIGHT) IN(
    SELECT
        STU_DEPT,
        MAX(STU_HEIGHT)
    FROM STUDENT
    GROUP BY STU_DEPT
);

-- 각 직급별 가장 높은 급여를 받는 교수의 이름, 직급, 급여 출력
SELECT * FROM PROFESSOR;
SELECT 
    NAME, POSITION, PAY
FROM PROFESSOR
WHERE (POSITION, PAY) IN (
    SELECT
        POSITION,
        MAX(PAY)
    FROM PROFESSOR
    GROUP BY POSITION    
);

-- 시험점수가 본인의 학과 평균 점수보다 높음 평균점수를 가진 학생들의 학번, 이름, 평균 점수 출력
SELECT 
    STU_DEPT,
    AVG(ENR_GRADE) AS DEPT_SCORE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;

SELECT 
    S.STU_NO, STU_NAME, S.STU_DEPT, AVG(ENR_GRADE) AS AVG_SCORE,
    DEPT_SCORE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN (
    SELECT 
        STU_DEPT,
        AVG(ENR_GRADE) AS DEPT_SCORE
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_DEPT
) T ON T.STU_DEPT = S.STU_DEPT
GROUP BY S.STU_NO, STU_NAME, S.STU_DEPT, DEPT_SCORE
HAVING AVG(ENR_GRADE) > DEPT_SCORE
ORDER BY S.STU_DEPT;

-- 예시
SELECT
    STU_NO, STU_NAME, STU_DEPT
FROM STUDENT;

SELECT *
FROM(
    SELECT
    STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
);

-- 본인 학과의 평균 키보다 큰 학생들 출력
SELECT 
    STU_DEPT,AVG(STU_HEIGHT)AS DEPT_HEIGHT
FROM STUDENT
GROUP BY STU_DEPT;

SELECT STU_NO, STU_NAME, S.STU_DEPT, STU_HEIGHT, DEPT_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT 
        STU_DEPT,AVG(STU_HEIGHT)AS DEPT_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT
WHERE STU_HEIGHT > DEPT_HEIGHT;











