-- SELF JOIN (자가 조인)
SELECT 
    E1.EMPNO, E1.ENAME, E2.ENAME
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;
 --
SELECT * FROM DEPARTMENT D;
SELECT * FROM STU;

-- 학과, 학부, 대학
SELECT 
    D1.DNAME,D2.DNAME,D3.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;

-- 공과대학에 속한 학생들 출력(주전공 - DEPTNO1 기준)
SELECT 
    D1.DNAME,D2.DNAME,D3.DNAME
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학';

-- 각 대학별(공과대학, 인문대학) 교수의 수 구하기
SELECT
    D3.DNAME,
    COUNT(*)
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
GROUP BY D3.DNAME;

-- 본인의 무하직원수 구하기(이름, 부하직원 수) EMP 테이블
SELECT 
    E1.ENAME,COUNT(*)
FROM EMP E1
INNER JOIN EMP E2 ON E1.EMPNO = E2.MGR
GROUP BY E1.EMPNO, E1.ENAME;











