SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

-- 학번, 학생이름, 학과, 담당교수명 출력
SELECT 
    STUNO, S.NAME, DNAME, P.NAME
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO;

-- 각 학과별 학생 수 출력(학과명, 학생수)
SELECT 
    DNAME, COUNT(*) AS 학생수
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
GROUP BY DNAME;

